{% set name = "pytest-order" %}
{% set version = "1.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest-order-{{ version }}.tar.gz
  sha256: 139d25b30826b78eebb42722f747eab14c44b88059d7a71d4f79d14a057269a5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - pytest >=3.7
  run:
    - pytest >=3.7
    - python >=3.6

test:
  imports:
    - pytest_order
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mrbean-bremen/pytest-order
  summary: pytest plugin to run your tests in a specific order
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
