context:
  name: pytest-order
  version: 1.3.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 51608fec3d3ee9c0adaea94daa124a5c4c1d2bb99b00269f098f414307f23dde

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - pytest >=5.0
    - setuptools
  run:
    - python >=${{ python_min }}
    - pytest >=5.0

tests:
  - python:
      imports:
        - pytest_order
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: pytest plugin that allows to customize the test execution order
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/pytest-dev/pytest-order
  documentation: https://pytest-order.readthedocs.io/

extra:
  recipe-maintainers:
    - hadim
    - mrbean-bremen
